version: '3.8'

services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - library-network
    environment:
      - SPRING_PROFILES_ACTIVE=default

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8080"
    networks:
      - library-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/user
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://discovery-server:8761/eureka

  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "8082:8080"
    networks:
      - library-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=database
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://discovery-server:8761/eureka

  borrowing-service:
    build: ./borrowing-service
    container_name: borrowing-service
    ports:
      - "8083:8080"
    networks:
      - library-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/borrowing_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=database
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - library-network
    depends_on:
      - discovery-server
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka


  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - library-network
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database
      POSTGRES_DB: book-service
    ports:
      - "5433:5432"
    networks:
      - library-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: database
      MYSQL_DATABASE: borrowing_db
    ports:
      - "3306:3306"
    networks:
      - library-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  library-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:
  mysql-data: