server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: borrowing-service
          uri: lb://borrowing-service
          predicates:
            - Path=/borrowings/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
