spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: postgres
    password: database
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8082