server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/user

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka