server:
  port: 8083

spring:
  application:
    name: borrowing-service
  datasource:
    url: jdbc:mysql://mysql/borrowing_db
    username: root
    password: database
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka